# site setting

title: Please-type-your-Github-name-here's Blog

remote_theme: jekyll/minima

show_description: true

header_pages:
  - all-tags.md
  - archive.md
  - about.md

plugins:
  - jekyll-toc